### ISSUE TITLE
Conda package for simplified bundling into other projects

### ISSUE THREAD

**Issue by robdmc** [astroML/gatspy#12]
Hello.

I just released a package https://github.com/robdmc/pandashells that depends on gatspy.  Since many of the tools in Pandashells depend on matplotlib and friends, I really want to make a conda package out of it.  I spent a little time trying to figure out how to include pip packages in conda, but I think that may be a fools errand.

Have you considered creating/maintaining a conda package out of gatspy?  I see one version on anacoda.org, but it doesn't seem to be maintained by you.

**Comment by jakevdp** [comment]
I haven't thought about maintaining that, because gatspy is a lightweight pure python code and won't benefit from having a conda binary. My impression has been that conda is mostly useful for packages with compiled extensions.

**Comment by robdmc** [comment]
Fair enough.  Thanks for writing the package.  I've been meaning to write a fast lomb-scargle tool for a while, and now I don't have to.   I think I may have figured out a way to include it in my conda package after all, we'll see. 

Thanks for response.  I'll close the issue.

**Comment by jakevdp** [comment]
great – if you can't figure out a way to include it as a dependency, let me know and we'll try to work it out.
