### ISSUE TITLE
Soften `supersmoother` requirement?

### ISSUE THREAD

**Issue by bnaul** [astroML/gatspy#23]
Related to #13, but slightly different: is there a not-too-hacky way to make `gatspy.periodic` be imported successfully without `supersmoother` being installed? It seems like if we just want to use, say, `LombScargle`, we should be able to do so without installing `supersmoother`. Maybe we could move the `ImportError` into the `SuperSmoother` class somewhere? Not a huge issue as `supersmoother` is quite light-weight, but would make things a little cleaner for some users.

**Comment by jakevdp** [comment]
That would certainly be a possibility – let me take a look.

**Comment by jakevdp** [comment]
I made this change here: https://github.com/astroML/gatspy/commit/6fb776c241c1b5157d3e62efae40784faae2d9fd

**Comment by bnaul** [comment]
:+1: :clap:

**Comment by bnaul** [comment]
I noticed there's a line `Make astroML a soft dependency` in `CHANGES.md`, might want to add something similar for this.

**Comment by jakevdp** [comment]
Will do – thanks!
