### ISSUE TITLE
cannot import name 'datasets'

### ISSUE THREAD

**Issue by ImmanuelSamuel** [astroML/gatspy#24]
Any idea why this is the case?

**Comment by jakevdp** [comment]
Can you paste the whole traceback here? Thanks

**Comment by adrn** [comment]
FYI: my student ran in to this issue as well. It looks like it's because Brani's website is gone. 

This is now a broken link:
http://www.astro.washington.edu/users/bsesar/S82_RRLyr/

Referenced here:
https://github.com/astroML/gatspy/blob/master/gatspy/datasets/rrlyrae.py

**Comment by jakevdp** [comment]
Closed by https://github.com/astroML/gatspy/pull/26
