### ISSUE TITLE
How to return higher Fourier parameters with LombScargle()?

### ISSUE THREAD

**Issue by hangcidu** [astroML/gatspy#41]
Sorry for this simple question, but how to return the Fourier parameters after it has been fitted with LombScargle()?

![download](https://user-images.githubusercontent.com/17509207/95954209-8570a000-0e2d-11eb-94cd-f5c0ee32a287.png)

**Comment by jakevdp** [comment]
I would suggest using astropy's lomb-scargle. The `model_parameters()` function will give you what you want; see https://docs.astropy.org/en/stable/timeseries/lombscargle.html
